apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: jvsf2g52b-go 
  janus-idp.io/tekton: jvsf2g52b-go
  backstage.io/kubernetes-id: jvsf2g52b-go
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: jvsf2g52b-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml